### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cybersecurity99** [Center-Sun/suricata-kafka-output#1]
Hi bro
I tried this bit got this
error: couldn't read /home/jason/oisf/code/suricata/master-6.0.x/rust/src/lib.rs: No such file or directory (os error 2)

error: could not compile `suricata` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Center-Sun** [comment]
You seem to have solved it, we can manually declare the location of the source code in Cargo.toml like this
`suricata = {version = "6.0.4-alpha", package = "suricata", path="/opt/src/suricata-6.0.4/rust"}`
